---
grails:
    profile: web
    codegen:
        defaultPackage: dk.renner.website
    spring:
        transactionManagement:
            proxies: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password:

environments:
    development:
        hibernate:
            dialect: 'org.hibernate.dialect.PostgreSQL9Dialect'
        dataSources:
            dataSource:
                logSql: true
                dbCreate: none
                url: jdbc:postgresql://localhost:5432/website
                username: website_app
                password: website_app
                driverClassName: org.postgresql.Driver

            adm:
                dbCreate: none
                url: jdbc:postgresql://localhost:5432/website
                username: website_adm
                password: website_adm
                driverClassName: org.postgresql.Driver
        grails:
            plugin:
                databasemigration:
                    adm:
                        updateOnStart: false
                        updateOnStartDefaultSchema: website
                        changelogFileName: changelog-adm.groovy
    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    production:
        hibernate:
            dialect: 'org.hibernate.dialect.PostgreSQL9Dialect'
        dataSources:
            dataSource:
                logSql: true
                dbCreate: none
                url: jdbc:postgresql://postgres:5432/website
                username: website_app
                password: website_app
                driverClassName: org.postgresql.Driver

            adm:
                dbCreate: none
                url: jdbc:postgresql://postgres:5432/website
                username: website_adm
                password: website_adm
                driverClassName: org.postgresql.Driver
        grails:
            plugin:
                databasemigration:
                    adm:
                        updateOnStart: false
                        updateOnStartDefaultSchema: website
                        changelogFileName: changelog-adm.groovy


# Added for the Spring Security Core plugin:
---
grails:
  plugin:
    springsecurity :
      auth.loginFormUrl: '/login'
      failureHandler.defaultFailureUrl: '/login?error=true'
      logout.filterProcessesUrl: '/logout'
      userLookup.userDomainClassName: 'dk.renner.website.user.User'
      userLookup.authorityJoinClassName: 'dk.renner.website.user.UserRole'
      authority.className: 'dk.renner.website.user.Role'
      adh.errorPage: '/user/denied'
      controllerAnnotations.staticRules:
        # TODO REVIEW: '/**' pattern matches everything, making everything insecure by default,
        # but '/' doesn't work, so this is needed for now to access frontpage without being logged in,
        # therefor all controllers needing security, need to be annotated with '@Secured('ROLE')'.
        - pattern: '/**'
          access: ['permitAll']
        - pattern: '/login'
          access: ['permitAll']
        - pattern: '/logout'
          access: ['permitAll']
        - pattern: '/login/**'
          access: ['permitAll']
        - pattern: '/scribbler'
          access: ['permitAll']
        - pattern: '/scribbler/**'
          access: ['permitAll']
        - pattern: '/assets/**'
          access: ['permitAll']